### ISSUE TITLE
wiki link with partial search

### ISSUE THREAD

**Issue by alperyilmaz** [vhp/terminal_velocity#6]
Hi,
First of all, I'd like to thank you a lot, since I'm using terminal velocity quite extensively.

I watched a video, where authors use [Zettelkasten method](http://zettelkasten.de/posts/zettelkasten-improves-thinking-writing/) with nvALT. In the [video](https://www.youtube.com/watch?v=ZKNyirFHVAU&t=34m39s) author has a contents of a book where notes are linked with wiki style links (i.e. `[[ ]]`). When  a link is clicked, nvALT makes a search and shows resulting note. The beauty of this part is the wiki link can be an id (e.g. `[[201706090700]]`) and it can match a note with the title containing the id `[[201706090700 an important note]]`.

So, I was wondering if it's possible to have links between files in terminal velocity? Having wiki style links within markdown context might be confusing or problematic but still I still wanted to ask.

Thanks.

**Comment by vhp** [comment]
Hi Alper,

I know what you're looking for. I'm afraid Terminal velocity is nowhere 
near as smart as would be needed for such features. The code pretty much 
gives the nice UI with search and selection, and it also handles the 
files in the background. That's about it. There's no higher presence of 
what's in the files or what files there are.

If your goal is an interlinking wiki but one that's terminal based. I'd 
recommend VimWiki. https://github.com/vimwiki/vimwiki

It will do just what you're looking for. Now I'm sure you can also use 
terminal-velocity ontop of it. But really you don't need to because you 
can do all the searching in vim.

Vim itself is also very programmable. Vimscript is a treat to work with. 
I really don't think it would be hard to write a small function in vim 
to help you link docs. This would be outside of terminal velocity and 
only be aware of the directory you want to work within. You may have a 
specific key combination to bring up a search. This could then search 
files in a directory you set in .tvrc or ,vimrc. As it searches it could 
find a file and it could auto create the link in the format you 
mentioned. I'm sure the code exists in Vimwiki already actually. It may 
need some molding but it could be done.

At the time don't have the free time to add to terminal velocity. Work 
is very busy now. Let me know how it goes.


Alper Yilmaz wrote on 06/08/2017 11:53 PM:

**Comment by firecat53** [comment]
[This](https://github.com/mmai/wikilink) vim plugin works well to link between files without using vimwiki. If you just use filenames, the vim command `gf` will go to the file under the cursor. @vhp is correct: tv probably isn't the right 'style' of notes manager to handle wiki links.

**Comment by Mooie** [comment]
If you are still interested in this six years on, I've forked mmai's original wikilink Vim plugin mentioned above to work with partial filenames. So [[201706090700]] would work to find a file named "201706090700 an important note". (In the original plugin, you needed to put the whole filename in the link.) You can find my fork [here](https://github.com/Mooie/wikilink2).
