### ISSUE TITLE
Add print file option

### ISSUE THREAD

**Issue by paul-mesnilgrente** [vhp/terminal_velocity#9]
Hello,

I am using your application to store some programming memos. It is really good. But some times, I don't want to open the editor, I just want to `cat` the file in the terminal.

It would be a great improvement to add this possibility when selecting a file.

What do you think about it?

**Comment by vhp** [comment]
Hi Paul,

Thank you for the suggestion. This is a bit hard to achieve actually due 
to the ncurses interface. To explore the possibility. Lets say you open 
terminal-velocity, press the down arrow a few times and then select the 
note you want with an enter. We currently open the editor of your choice 
and then when closed go right back to the ncurses interface. If cat were 
an option it would be very confusing for people to find their way back 
to terminal-velocity. It would essentially have to open a new terminal 
or exit the program. An exec could be an option too.

I really see the use of an editor like vim/emacs as a plus in this use 
case. The reason is you get syntax highlighting which can make your 
notes easier to read especially if they are in markdown.

One option we could use is a paging program like less or more. But at 
that point I have to question the need for added complexity. Most 
editors also page and to exit less/more you still need press a special 
key (q).  When in vim it would be :q.

It really seems like a lot of work to save the pressing of one key along 
with the loss of syntax highlighting and stuff. Plus it adds more 
complexity to code and UI for users.

Happy to hear your thoughts. Thanks

Vincent

**Comment by paul-mesnilgrente** [comment]
Sorry about that, I forgot this issue.

I think that I understand your point of view. I think that it depends of your use of terminal_velocity.

I usually open it, search for a memo, look for the information and exit it. In this use case, a simple cat/more/less is enough. What should be done is only execute this command and exit terminal_velocity or eventually take it back with the use of an exec as you said.

For the syntax highlighting, you can always use `python-pygments` which is a good syntax highlighter for the terminal. I use it with an alias (`ccat` for colored cat) to cat source files.

In order to choose between vim or a cat, you could use another key as enter like `c` for cat or `Suppr` if you don't want a key that is already taken by the actual program.

But it's only a proposition ^^
